name: Deploy to AWS Lambda

on:
  push:
    branches: [ ML/Infra ]

jobs:
  build-ecr:
    runs-on: ubuntu-latest
    environment: AWS
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # Public ECR is us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform/ecr # Path to your .tf files

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./terraform/ecr
      

  push-ecr:
    runs-on: ubuntu-latest
    environment: AWS
    needs: build-ecr
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # Public ECR is us-east-1

      - name: Login to Amazon Public ECR
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: private

      - name: Check if ECR Repository Exists
        id: check-image
        env:
          ECR_REPOSITORY: my-lambda-app
        run: |
          if aws ecr describe-images --repository-name $ECR_REPOSITORY --image-ids imageTag=latest > /dev/null 2>&1; then
            echo "ECR Image already exists. Skipping build."
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "ECR Image does not exist."
            echo "exists=false" >> $GITHUB_OUTPUT
          fi


      - name: Build, Tag, and Push Image
        env:
          ECR_REGISTRY: ${{ secrets.ECR_ALIAS }}.dkr.ecr.us-east-1.amazonaws.com
          ECR_REPOSITORY: my-lambda-app
          IMAGE_TAG: ${{ github.sha }}
        if: steps.check-image.outputs.exists == 'false'
        working-directory: ./app
        run: |
          # Build and push using the commit SHA as the tag for better versioning
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          
          # Also update the 'latest' tag
          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:latest
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

  build-lambda:
    needs: push-ecr
    runs-on: ubuntu-latest
    environment: AWS
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: setup terraform
        uses: hashicorp/setup-terraform@v3

      - name: Init Terraform Lambda
        working-directory: ./terraform/lambda
        run: terraform init
        
      - name: Apply Terraform Lambda
        working-directory: ./terraform/lambda
        run: terraform apply -auto-approve
        